config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  devise_for :users
  resources :users

  resources :foods
  resources :recipe_foods
  root 'foods#index'

  get 'public_recipes', to: 'recipes#public_recipes'
 # get 'shopping_list', to: 'shopping_list#shopping_list' 

  get 'general_shopping_list', to: 'recipes#shopping_list'

 # get 'recipes/new', to: 'recipes#new' 
 # post 'recipes/new', to: 'recipes#create' 


end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user

  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :price, presence: true
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/food_controller.rb
class FoodController < ApplicationController
  def index; end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id
    if @food.save
      redirect_to foods_path
    else
      render 'new'
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity, :user_id)
  end
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/food/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Recipe App', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item px-3">
            <%= link_to 'Food', root_path, class:"nav-link active" %>
          </li>

          <li class="nav-item px-3"> 
          <%= link_to 'Public Recipes',  public_recipes_path, class:"nav-link active" %>
          </li>

          <li class="nav-item px-3"> 
          <%= link_to 'Recipes', recipes_path, class:"nav-link active" %>
          </li>
          
          <li class="nav-item px-3">
            <%= button_to "LogOut", destroy_user_session_path, { method: :delete, data: { turbo:false }}  %>
          </li>
        <% else %>

          <li class="nav-item px-3">
          <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link active" %>
          </li>

          <li class="nav-item px-3">
              <%= link_to "LogIn", user_session_path, class:"nav-link active" %>
          </li>
        <% end %>

      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/food/index.html.erb
<div class:"container">
    <div class:"container">
        <%= link_to 'Add Food', new_food_path, class:"btn btn-primary" %>
    </div>

</div>