config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  devise_for :users
  resources :users

  resources :foods
  resources :recipe_foods
  root 'foods#index'

  get 'public_recipes', to: 'recipes#public_recipes'
 # get 'shopping_list', to: 'shopping_list#shopping_list' 

  get 'general_shopping_list', to: 'recipes#shopping_list'

 # get 'recipes/new', to: 'recipes#new' 
 # post 'recipes/new', to: 'recipes#create' 


end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  has_many :recipe_foods
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
  validates :preparation_time, presence: true

  validates :cooking_time, presence: true

  validates :description, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  def public_recipes
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
    @ingredients = @recipe.recipe_foods
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  def shopping_list
    @recipes = current_user
    @new_ingredients_data, @new_ingredients_price = current_user.new_ingredients_information
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      redirect_to recipes_path
    else
      render 'new'
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public, :user_id)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group  p-2">
    <%= form.text_field :name, class: "form-control", placeholder: "Name" %>
  </div>


  <div class="field form-group  p-2">
    <%= form.text_field :preparation_time, class: "form-control", placeholder: "Preparation time" %>
  </div>


  <div class="field form-group  p-2">
    <%= form.text_field :cooking_time, class: "form-control", placeholder: "Cooking time" %>
  </div>


  <div class="field form-group  p-2">
    <%= form.text_field :description, class: "form-control", placeholder: "Description" %>
  </div>

  <div class="field form-group  p-2">
    <%= form.check_box :public %>
    <%= form.label :public, style: "display: inline" %>
  </div>


  <div class="field form-group  p-2">
  <%= form.number_field :user_id, id: :recipe_user_id, class: "form-control", value: current_user.id, type: :hidden %>
  </div> 

  <div>
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>Name:</strong>
    <%= recipe.name %>
  </p>

  <p>
    <strong>Preparation time:</strong>
    <%= recipe.preparation_time %>
  </p>

  <p>
    <strong>Cooking time:</strong>
    <%= recipe.cooking_time %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

  <p>
    <strong>Public:</strong>
    <%= recipe.public %>
  </p>

</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="d-flex justify-content-between p-2">
  <h2>RECIPE LIST</h2>
  <%= link_to 'Add Recipe', new_recipe_path, class:"btn btn-success btn-lg" %>
</div>

<div id="recipes">
  <% @recipes.each do |recipe| %>
    <% if current_user.id == recipe.user_id%>
      <div class="container">
        <div class="row justify-content-start">
          <div class="col-sm-3 p-2 border border-secondary">
            <h3> <%= link_to recipe.name, recipe %> </h3>
            <span> <%= button_to "Remove", recipe, method: :delete, class:"btn btn-danger" %></span>
          
          </div>
          <div class="col-sm-9 p-2 border border-secondary">
            <span> <%= recipe.description %> </span>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/public_recipes.html.erb
<p style="color: green"><%= notice %></p>

<div class="d-flex justify-content-between p-2">
  <h2>PUBLIC RECIPE</h2>
</div>

<div id="recipes">
  <% @recipes.each do |recipe| %>
    <%if can? :read, recipe%>
    <div class="container">
      <div class="row justify-content-start">
        <div class="col-sm-3 p-2 border border-secondary">
          <h3> <%= recipe.name %></h3>
          <h6>Made By: <%= recipe.user.name %></h6>
        </div>
        <div class="col-sm-9 p-2 border border-secondary">
          <p>Total food items: <%=recipe.recipe_foods.count%></p>
          <p>Total price:
            <%a = 0%>
            <% recipe.recipe_foods.each do |recipefood| %>
            <% a += recipefood.food.price.to_int %>
            <%end%>
            <%= a%> $
          </p>   
            <span><%= link_to 'View', recipe_path(recipe), class: "btn btn-outline-success" %></span>  
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/recipes/shopping_list.html.erb
<section id="public-recipes-list">
  <%= link_to "Back to recipe", :back %>
  <h1> Shopping List </h1>

  <div>
    <p>Amount of food items to buy: <%= @new_ingredients_data.length %></p>
    <p>Total value needed: <%= @new_ingredients_total_price %></p>
  </div>

  <% if @new_ingredients_data.empty?%>
    <p>You have all the ingredients necessary to do all your recipes!</p>
  <% else %>
  <table class="table table-striped table-bordered table-hover">
  <thead class="table-secondary">
    <tr>
      <th><table class="table table-striped table-bordered table-hover">
      <thead class="table-dark">
        <tr>
          <th>Name</th>
          <th>Quantity unit</th>
          <th>Price</th>
        <tr>
      </thead>
      <tbody>
      <% @new_ingredients_data.each do |ingredient| %>
        <tr>
          <td> <%= ingredient[:name] %> </td>
          <td> <%= ingredient[:quantity] %> </td>
          <td> <%= ingredient[:price] %> </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</section>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>


<div class="container">
  <div class="d-flex justify-content-center p-2">
    <h1><%= @recipe.name %></h1>
  </div>

  <div class="d-flex justify-content-between p-2">
    <h4>Preparation time: <%= @recipe.preparation_time %> hours</h4>
  </div>

  <div class="d-flex justify-content-between p-2">
    <h4>Cooking time<%= @recipe.cooking_time %> hours</h4>
  </div>

  <div class="d-flex justify-content-between p-2">
    <h4>Steps go here...</h4>
  </div>

  <hr>

  <div class="d-flex justify-content-between p-2">
    <span><%= link_to 'Generate Shopping List', general_shopping_list_path, class:"btn btn-secondary btn-lg" %></span>
    <span><%= link_to 'Add Ingredient', new_recipe_food_url(current_user, @recipe) , class:"btn btn-secondary btn-lg" %></span>

  </div>
  

</div>


<hr class="line" />

<div class="container mt-5">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">Value</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @recipe.recipe_foods.each do |recipe_food| %>
      <tr>
        <td><%= recipe_food.food.name %></td>
        <td><%= recipe_food.food.quantity %></td>
        <td><%= recipe_food.food.price %></td>
        <td><%= link_to 'Modify', edit_food_path(recipe_food.food) ,class: "btn btn-outline-primary underline" %>
          <span><%= link_to 'Remove', food_path(recipe_food.food), data: { turbo_method: 'delete', turbo_confirm: "Are you sure to delete" }, class: "btn btn-outline-danger underline" %></span>
        </td>
      </tr>
    </tbody>
    <%end%>
  </table>
</div>