config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  devise_for :users
  resources :users

  resources :foods
  resources :recipe_foods
  root 'foods#index'

  get 'public_recipes', to: 'recipes#public_recipes'
 # get 'shopping_list', to: 'shopping_list#shopping_list' 

  get 'general_shopping_list', to: 'recipes#shopping_list'

 # get 'recipes/new', to: 'recipes#new' 
 # post 'recipes/new', to: 'recipes#create' 


end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 1 }

  def total_price
    quantity * food.price
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_food, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /recipe_foods or /recipe_foods.json
  def index
    @recipe_foods = RecipeFood.all
  end

  # GET /recipe_foods/1 or /recipe_foods/1.json
  def show; end

  # GET /recipe_foods/new
  def new
    @recipe_food = RecipeFood.new
  end

  # GET /recipe_foods/1/edit
  def edit; end

  # POST /recipe_foods or /recipe_foods.json
  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    if @recipe_food.save
      redirect_to recipe_foods_path
    else
      render 'new'
    end
  end

  # PATCH/PUT /recipe_foods/1 or /recipe_foods/1.json
  def update
    respond_to do |format|
      if @recipe_food.update(recipe_food_params)
        format.html { redirect_to recipe_food_url(@recipe_food), notice: 'Recipe food was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe_food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe_food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_foods/1 or /recipe_foods/1.json
  def destroy
    @recipe_foods = RecipeFood.find(params[:id])
    @recipe_food.destroy
    redirect_to recipe_foods_path
    #  respond_to do |format|
    #    format.html { redirect_to recipe_foods_url, notice: "Recipe food was successfully destroyed." }
    #   format.json { head :no_content }
    #  end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :recipe_id, :food_id)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/_form.html.erb
  <%= form_with model: @recipe_food, url: recipe_foods_path, method: :post do |form| %>
    <% if recipe_food.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>
  
        <ul>
          <% recipe_food.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field form-group  p-3">
      <%= form.label 'Ingredient', style: "display: block" %>
      <select name="recipe_food[food_id]">
        <% current_user.foods.each do |food| %>
          <option value=<%= food.id %>><%= food.name %></option>
        <% end %>
      </select>
    </div>
  
    <div class="field form-group  p-3">
      <%= form.label :quantity, style: "display: block" %>
      <%= form.number_field :quantity %>
    </div>

    <div class="field form-group  p-3">
      <%= form.label :recipe_id , style: "display: block" %>
      <%= form.number_field :recipe_id %>
    </div>

  
    <div class="field form-group  p-3">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>
  

app/views/recipe_foods/_recipe_food.html.erb
<div id="<%= dom_id recipe_food %>">
  <p>
    <strong>Quantity:</strong>
    <%= recipe_food.quantity %>
  </p>

</div>

app/views/recipe_foods/edit.html.erb
<h1>Editing recipe food</h1>

<%= render "form", recipe_food: @recipe_food %>

<br>

<div>
  <%= link_to "Show this recipe food", @recipe_food %> |
  <%= link_to "Back to recipe foods", recipe_foods_path %>
</div>

app/views/recipe_foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipe foods</h1>

<div class="container mt-5">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Quantity</th>
        <th scope="col">food_id</th>
        <th scope="col">recipe_id</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @recipe_foods.each do |recipe_food| %>
      <tr>
        <td><%= recipe_food.quantity %></td>
        <td><%= recipe_food.food.name %></td>
        <td><%= recipe_food.recipe.name %></td>
        <td><%= link_to 'Modify', class: "btn btn-outline-danger" %><span><%= link_to 'Remove', class: "btn btn-outline-danger" %></span></td>
      </tr>
    </tbody>
    <%end%>
  </table>
</div>

app/views/recipe_foods/new.html.erb
<section id="public-recipes-list">
  <h1>Select one ingredient from your food list</h1>

  <%= render "form", recipe_food: @recipe_food %>

  <br>

  <div>
    <%= link_to "Back to recipe", :back %>
  </div>
</section>

app/views/recipe_foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe_food %>

<div>
  <%= link_to "Edit this recipe food", edit_recipe_food_path(@recipe_food) %> |
  <%= link_to "Back to recipe foods", recipe_foods_path %>

  <%= button_to "Destroy this recipe food", @recipe_food, method: :delete %>
</div>